#ifndef _INCLUDED_SRIC_CMDS
#define _INCLUDED_SRIC_CMDS

/* System commands */
enum {
	SRIC_SYSCMD_RESET,
	SRIC_SYSCMD_TOK_ADVANCE,
	SRIC_SYSCMD_ADDR_ASSIGN,
	SRIC_SYSCMD_ADDR_INFO,
};

#endif	/* _INCLUDED_SRIC_CMDS */
