#ifndef _INCLUDED_SRIC_CMDS
#define _INCLUDED_SRIC_CMDS

/* System commands */
enum {
	SRIC_SYSCMD_RESET,
	SRIC_SYSCMD_TOK_ADVANCE,
	SRIC_SYSCMD_ADDR_ASSIGN,
	SRIC_SYSCMD_ADDR_INFO,
};

/* Gateway control commands */
enum {
	GW_CMD_USE_TOKEN,
	GW_CMD_REQ_TOKEN,
	GW_CMD_HAVE_TOKEN,
	GW_CMD_GEN_TOKEN,
};

#endif	/* _INCLUDED_SRIC_CMDS */
